import httpx
from app.core.config import settings
import logging
import base64
from pathlib import Path

logger = logging.getLogger("uvicorn")

BREVO_API_URL = "https://api.brevo.com/v3/smtp/email"


async def send_report_via_brevo(
    doctor_email: str,
    doctor_name: str,
    user_email: str,
    report_content: str,
    severity_score: int = 3,
    docx_path: str = None
) -> bool:
    """
    Send the clinical trauma report to both the doctor and the user
    using the Brevo Transactional Email API.
    Optionally attaches the Word document report.
    
    Returns True if email was sent successfully, False otherwise.
    """
    
    # Build HTML email body
    html_body = f"""
    <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 700px; margin: 0 auto; padding: 24px; background: #f8f9fa;">
        <div style="background: #ffffff; border-radius: 12px; padding: 32px; box-shadow: 0 2px 8px rgba(0,0,0,0.08);">
            <div style="text-align: center; margin-bottom: 24px;">
                <h1 style="color: #1a1a2e; margin: 0; font-size: 24px;">TraumaAI Clinical Report</h1>
                <p style="color: #6c757d; margin: 4px 0 0;">Generated by Anovaidya AI Trauma Assistant</p>
            </div>
            
            <div style="background: {'#dc3545' if severity_score >= 4 else '#ffc107' if severity_score >= 3 else '#28a745'}; 
                        color: white; padding: 12px 20px; border-radius: 8px; text-align: center; margin-bottom: 20px;">
                <strong>Severity Level: {severity_score}/5</strong>
            </div>
            
            <div style="line-height: 1.7; color: #333; white-space: pre-wrap;">
{report_content}
            </div>
            
            <hr style="border: none; border-top: 1px solid #e9ecef; margin: 24px 0;">
            
            <p style="font-size: 12px; color: #999; text-align: center;">
                This report was auto-generated by TraumaAI (Anovaidya). 
                The patient has been advised to seek professional medical attention.
            </p>
        </div>
    </div>
    """
    
    payload = {
        "sender": {
            "name": "TraumaAI - Anovaidya",
            "email": "harish13032003@gmail.com"
        },
        "to": [
            {"email": doctor_email, "name": doctor_name},
            {"email": user_email, "name": "Patient"}
        ],
        "subject": f"[TraumaAI] Clinical Trauma Report — Severity {severity_score}/5",
        "htmlContent": html_body
    }

    # Attach Word document if available
    if docx_path:
        docx_file = Path(docx_path)
        if docx_file.exists():
            try:
                with open(docx_file, "rb") as f:
                    content_bytes = f.read()
                encoded = base64.b64encode(content_bytes).decode("utf-8")
                payload["attachment"] = [{
                    "content": encoded,
                    "name": docx_file.name,
                    "type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
                }]
                logger.info(f"[BREVO] Attaching Word document: {docx_file.name}")
            except Exception as e:
                logger.warning(f"[BREVO] Could not attach docx: {e}")
    
    headers = {
        "accept": "application/json",
        "content-type": "application/json",
        "api-key": settings.BREVO_API_KEY
    }
    
    try:
        async with httpx.AsyncClient(timeout=15.0) as client:
            response = await client.post(BREVO_API_URL, json=payload, headers=headers)
        
        if response.status_code in (200, 201):
            logger.info(f"[BREVO] Email sent successfully to {doctor_email} and {user_email}")
            return True
        else:
            logger.error(f"[BREVO] Email failed. Status: {response.status_code} | Body: {response.text}")
            return False
            
    except Exception as e:
        logger.error(f"[BREVO] Request failed: {e}")
        return False
