"""
Word Document Generator for Clinical Reports
=============================================
Uses python-docx to create professional, editable .docx reports
from the Gemini-generated clinical report text.
"""

import logging
import os
import re
from datetime import datetime
from pathlib import Path
from typing import Optional

from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT

logger = logging.getLogger("uvicorn")

# Directory to store generated reports
UPLOADS_DIR = Path(__file__).resolve().parent.parent.parent / "uploads" / "reports"
UPLOADS_DIR.mkdir(parents=True, exist_ok=True)


def _add_styled_heading(doc: Document, text: str, level: int = 1):
    """Add a heading with custom styling."""
    heading = doc.add_heading(text, level=level)
    for run in heading.runs:
        run.font.color.rgb = RGBColor(0x0D, 0x6E, 0x4F)  # Medical green


def _parse_and_add_content(doc: Document, content: str):
    """
    Parse the markdown-ish report text from the LLM and convert it
    into well-formatted Word document elements.
    """
    lines = content.strip().split("\n")
    i = 0
    while i < len(lines):
        line = lines[i].strip()

        # Skip empty lines
        if not line:
            i += 1
            continue

        # Heading: ### or ## or #
        if line.startswith("###"):
            _add_styled_heading(doc, line.lstrip("#").strip(), level=3)
        elif line.startswith("##"):
            _add_styled_heading(doc, line.lstrip("#").strip(), level=2)
        elif line.startswith("#"):
            _add_styled_heading(doc, line.lstrip("#").strip(), level=1)

        # Horizontal rule
        elif line.startswith("---") or line.startswith("***"):
            doc.add_paragraph("_" * 60)

        # Bullet point
        elif line.startswith("- ") or line.startswith("* "):
            bullet_text = line[2:].strip()
            p = doc.add_paragraph(style="List Bullet")
            _add_formatted_runs(p, bullet_text)

        # Bold key-value line (e.g., **Date**: something)
        elif line.startswith("**"):
            p = doc.add_paragraph()
            _add_formatted_runs(p, line)

        # Normal paragraph
        else:
            p = doc.add_paragraph()
            _add_formatted_runs(p, line)

        i += 1


def _add_formatted_runs(paragraph, text: str):
    """
    Parse inline **bold** markers and add runs to the paragraph.
    """
    # Split on bold markers
    parts = re.split(r"(\*\*.*?\*\*)", text)
    for part in parts:
        if part.startswith("**") and part.endswith("**"):
            run = paragraph.add_run(part[2:-2])
            run.bold = True
            run.font.size = Pt(11)
        else:
            run = paragraph.add_run(part)
            run.font.size = Pt(11)


def generate_clinical_report_docx(
    report_content: str,
    user_id: str,
    session_id: str,
    doctor_name: Optional[str] = None,
    severity_score: Optional[int] = None,
    specialization: Optional[str] = None,
) -> Optional[str]:
    """
    Generate a professional Word document from the clinical report text.

    Returns the file path to the generated .docx, or None on failure.
    """
    try:
        doc = Document()

        # ── Page margins ─────────────────────────────────────────
        for section in doc.sections:
            section.top_margin = Inches(0.8)
            section.bottom_margin = Inches(0.8)
            section.left_margin = Inches(1.0)
            section.right_margin = Inches(1.0)

        # ── Title ────────────────────────────────────────────────
        title = doc.add_heading("Patient Trauma Report", level=0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        for run in title.runs:
            run.font.color.rgb = RGBColor(0x0D, 0x6E, 0x4F)

        subtitle = doc.add_paragraph()
        subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = subtitle.add_run("Generated by Anovaidya AI Trauma Assistant")
        run.font.size = Pt(10)
        run.font.color.rgb = RGBColor(0x66, 0x66, 0x66)

        # ── Metadata table ───────────────────────────────────────
        table = doc.add_table(rows=4, cols=2, style="Light Grid Accent 6")
        table.alignment = WD_TABLE_ALIGNMENT.CENTER

        meta = [
            ("Date", datetime.utcnow().strftime("%B %d, %Y — %H:%M UTC")),
            ("Severity Level", f"{severity_score}/5" if severity_score else "N/A"),
            ("Specialization", specialization or "General"),
            ("Selected Doctor / Facility", doctor_name or "N/A"),
        ]
        for row_idx, (key, val) in enumerate(meta):
            cell_key = table.cell(row_idx, 0)
            cell_val = table.cell(row_idx, 1)
            cell_key.text = key
            cell_val.text = val
            # Bold the key column
            for p in cell_key.paragraphs:
                for r in p.runs:
                    r.bold = True

        doc.add_paragraph("")  # Spacer

        # ── Report body ──────────────────────────────────────────
        _parse_and_add_content(doc, report_content)

        # ── Footer disclaimer ────────────────────────────────────
        doc.add_paragraph("")
        disclaimer = doc.add_paragraph()
        disclaimer.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = disclaimer.add_run(
            "This report was auto-generated by TraumaAI (Anovaidya). "
            "The patient has been advised to seek professional medical attention."
        )
        run.font.size = Pt(8)
        run.font.italic = True
        run.font.color.rgb = RGBColor(0x99, 0x99, 0x99)

        # ── Save ─────────────────────────────────────────────────
        safe_session = re.sub(r"[^a-zA-Z0-9_-]", "_", session_id)
        filename = f"trauma_report_{safe_session}.docx"
        filepath = UPLOADS_DIR / filename
        doc.save(str(filepath))

        logger.info(f"[DOCX] Report saved: {filepath}")
        return str(filepath)

    except Exception as e:
        logger.error(f"[DOCX] Generation failed: {e}")
        return None
